In [2]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np 
%matplotlib inline

In [3]:
data = pd.read_csv("C:/Users/aravi/Downloads/ML learning notes/Day7/continuos/credit_data.csv")

In [ ]:
data.head()

In [ ]:
data.describe()

In [ ]:
data.info()

In [ ]:
data.groupby('default').describe()

In [ ]:
fig,axes = plt.subplots(nrows =1,ncols =4 ,figsize=(20,5))

ax = sns.distplot(data['income'],ax = axes[0],bins = 50 )
ax.set_title('income')
ax.legend()
ax = sns.distplot(data['age'],ax= axes[1],bins = 50)
ax.set_title('age')
ax.legend()
ax = sns.distplot(data['loan'],ax = axes[2],bins = 50)
ax.set_title('loan')
ax.legend()
ax = sns.distplot(data['LTI'],ax = axes[3],bins = 50)
ax.set_title('lti')
ax.legend()

In [ ]:
data.isnull().sum()

# Gaussian 

In [ ]:
data['default'].plot(kind = 'kde')

In [4]:
X = data[['income','age','loan']]
y = data['default']

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [5]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
model = GaussianNB()

In [ ]:
model1 = model.fit(X_train,y_train)

In [ ]:
y_pred = model1.predict(X_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [ ]:
print(accuracy_score(y_test,y_pred))

In [ ]:
print(confusion_matrix(y_test,y_pred))

In [ ]:
print(classification_report(y_test,y_pred))

# Decision tree

In [18]:
from sklearn import tree

In [19]:
tree = tree.DecisionTreeClassifier()

In [ ]:
tree.fit(X_train,y_train)

In [ ]:
t_pred = tree.predict(X_test)

In [ ]:
print(accuracy_score(y_test,t_pred))

In [ ]:
print(confusion_matrix(y_test,t_pred))

In [ ]:
print(classification_report(y_test,t_pred))

# Random forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier()

In [ ]:
rfc.fit(X_train,y_train)

In [ ]:
r_pred = rfc.predict(X_test)

In [ ]:
print(accuracy_score(y_test,r_pred))

In [ ]:
print(confusion_matrix(y_test,r_pred))

In [ ]:
print(classification_report(y_test,r_pred))

# Logistic regression

In [9]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(X_train,y_train)

In [ ]:
lr_pred = lr.predict(X_test)

In [ ]:
print(accuracy_score(y_test,lr_pred))

In [ ]:
print(confusion_matrix(y_test,lr_pred))

In [ ]:
print(classification_report(y_test,lr_pred))

# Understanding which is perfect model

In [ ]:
def gausssian(y_test,y_pred):
    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))

In [ ]:
def descison():
    print(accuracy_score(y_test,t_pred))
    print(confusion_matrix(y_test,t_pred))
    print(classification_report(y_test,t_pred))


In [ ]:
def random():
    print(accuracy_score(y_test,r_pred))
    print(confusion_matrix(y_test,r_pred))
    print(classification_report(y_test,r_pred))

In [ ]:
def logistic():
    print(accuracy_score(y_test,lr_pred))
    print(confusion_matrix(y_test,lr_pred))
    print(classification_report(y_test,lr_pred))
     

In [41]:
from  sklearn import tree

In [42]:
def build_model(model_name,X_train,X_test,y_train,y_test):
    
    if model_name == "tree":
        model = tree.DecisionTreeClassifier()
    else:
        model = model_name()
        
    model = model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    
    

In [39]:
build_model(LogisticRegression,X_train,X_test,y_train,y_test)

0.9090909090909091
[[547  15]
 [ 45  53]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.95       562
           1       0.78      0.54      0.64        98

    accuracy                           0.91       660
   macro avg       0.85      0.76      0.79       660
weighted avg       0.90      0.91      0.90       660



In [45]:
build_model("tree",X_train,X_test,y_train,y_test)

0.9833333333333333
[[560   2]
 [  9  89]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       562
           1       0.98      0.91      0.94        98

    accuracy                           0.98       660
   macro avg       0.98      0.95      0.97       660
weighted avg       0.98      0.98      0.98       660



In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
build_model(RandomForestClassifier,X_train,X_test,y_train,y_test)

0.9848484848484849
[[562   0]
 [ 10  88]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       562
           1       1.00      0.90      0.95        98

    accuracy                           0.98       660
   macro avg       0.99      0.95      0.97       660
weighted avg       0.99      0.98      0.98       660



In [33]:
from sklearn.naive_bayes import GaussianNB

In [34]:
build_model(GaussianNB,X_train,X_test,y_train,y_test)

0.9257575757575758
[[553   9]
 [ 40  58]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.96       562
           1       0.87      0.59      0.70        98

    accuracy                           0.93       660
   macro avg       0.90      0.79      0.83       660
weighted avg       0.92      0.93      0.92       660



In [ ]:
build_model(LogisticRegression,X_train,X_test,y_train,y_test)

# Descision tree is a good model !

questions bellow:

In [ ]:
#doubt ; where we have to use the confusion and mean_error

In [ ]:
#encoding ? in mutlinomial

In [ ]:
#lambda function

In [ ]:
# to list

# spam vs ham

In [90]:
df = pd.read_csv("C:/Users/aravi/Downloads/ML learning notes/Day7/Multinomial/spam.csv")

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 135-136: invalid continuation byte

In [48]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [49]:
cols = {'v1':'class_label','v2':'message'}

In [50]:
df.rename(columns = cols ,inplace = True)

In [51]:
df.head()

class_label                                            message Unnamed: 2  \
0         ham  Go until jurong point, crazy.. Available only ...        NaN   
1         ham                      Ok lar... Joking wif u oni...        NaN   
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3         ham  U dun say so early hor... U c already then say...        NaN   
4         ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [52]:
df.drop(['Unnamed: 4'],axis = 1,inplace = True)

In [53]:
df.head()

class_label                                            message Unnamed: 2  \
0         ham  Go until jurong point, crazy.. Available only ...        NaN   
1         ham                      Ok lar... Joking wif u oni...        NaN   
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3         ham  U dun say so early hor... U c already then say...        NaN   
4         ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN

In [54]:
df.isnull().sum()

class_label       0
message           0
Unnamed: 2     5522
Unnamed: 3     5560
dtype: int64

In [55]:
df.value_counts()

class_label  message                                                                                                                                          Unnamed: 2                                                                    Unnamed: 3                                
spam         Your free ringtone is waiting to be collected. Simply text the password \MIX\" to 85069 to verify. Get Usher and Britney. FML                     PO Box 5249                                                                   MK17 92H. 450Ppw 16"                         2
ham          Edison has rightly said, \A fool can ask more questions than a wise man can answer\" Now you know why all of us are speechless during ViVa.. GM  GN                                                                            GE                                            2
             \Wen u miss someone                                                                                                                         

In [56]:
df.describe()

class_label                 message  \
count         5572                    5572   
unique           2                    5169   
top            ham  Sorry, I'll call later   
freq          4825                      30   

                                               Unnamed: 2 Unnamed: 3  
count                                                  50         12  
unique                                                 43         10  
top      bt not his girlfrnd... G o o d n i g h t . . .@"         GE  
freq                                                    3          2

In [57]:
df['class_label'].value_counts()

ham     4825
spam     747
Name: class_label, dtype: int64

In [58]:
df['class_label'] = df['class_label'].apply(lambda X: 1 if X == 'spam' else 0)

In [59]:
X = df['message']
y = df['class_label']

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
lst = X_train.tolist()

In [89]:
type(X_train)

pandas.core.series.Series

In [62]:
vectorizer = TfidfVectorizer(
input = lst,
lowercase = True,
stop_words = 'english'
)
features_train_transformed = vectorizer.fit_transform(lst)

features_test_transformed = vectorizer.transform(X_test)

# Multinomial

In [63]:
vectorizer.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '0578',
 '06',
 '07008009200',
 '07099833605',
 '07123456789',
 '0721072',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07808247860',
 '07808726822',
 '07821230901',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870162

In [64]:
from sklearn.naive_bayes import MultinomialNB

In [65]:
classifier = MultinomialNB()
classifier.fit(features_train_transformed, y_train)

MultinomialNB()

In [66]:
ypred_labels = classifier.predict(features_test_transformed)

In [67]:

    print(accuracy_score(y_test,ypred_labels))
    print('###################################')
    print(confusion_matrix(y_test,ypred_labels))
    print('###################################')
    print(classification_report(y_test,ypred_labels))

0.9641148325358851
###################################
[[1434    0]
 [  60  178]]
###################################
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1434
           1       1.00      0.75      0.86       238

    accuracy                           0.96      1672
   macro avg       0.98      0.87      0.92      1672
weighted avg       0.97      0.96      0.96      1672



# Descision treee

In [68]:
from sklearn import tree

In [69]:
tree = tree.DecisionTreeClassifier()

In [70]:
tree.fit(features_train_transformed,y_train)

DecisionTreeClassifier()

In [71]:
tt_pred = tree.predict(features_test_transformed)

In [72]:
print(accuracy_score(y_test,tt_pred))
print('###################################')
print(confusion_matrix(y_test,tt_pred))
print('###################################')
print(classification_report(y_test,tt_pred))

0.9605263157894737
###################################
[[1410   24]
 [  42  196]]
###################################
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1434
           1       0.89      0.82      0.86       238

    accuracy                           0.96      1672
   macro avg       0.93      0.90      0.92      1672
weighted avg       0.96      0.96      0.96      1672



# random forest

In [73]:
from sklearn.ensemble import RandomForestClassifier

In [74]:
rfc2 = RandomForestClassifier()

In [75]:
rfc2.fit(features_train_transformed, y_train)

RandomForestClassifier()

In [76]:
rfc2_pred = rfc2.predict(features_test_transformed)

In [77]:
print(accuracy_score(y_test,rfc2_pred))
print('###################################')
print(confusion_matrix(y_test,rfc2_pred))
print('###################################')
print(classification_report(y_test,rfc2_pred))

0.9694976076555024
###################################
[[1434    0]
 [  51  187]]
###################################
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1434
           1       1.00      0.79      0.88       238

    accuracy                           0.97      1672
   macro avg       0.98      0.89      0.93      1672
weighted avg       0.97      0.97      0.97      1672



# Logistic regression

In [78]:
from sklearn.linear_model import LogisticRegression

In [79]:
lr2 = LogisticRegression()

In [80]:
lr2.fit(features_train_transformed,y_train)

LogisticRegression()

In [81]:
lr2_pred = lr2.predict(features_test_transformed)

In [82]:
print(accuracy_score(y_test,lr2_pred))
print('###################################')
print(confusion_matrix(y_test,lr2_pred))
print('###################################')
print(classification_report(y_test,lr2_pred))

0.9527511961722488
###################################
[[1431    3]
 [  76  162]]
###################################
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      1434
           1       0.98      0.68      0.80       238

    accuracy                           0.95      1672
   macro avg       0.97      0.84      0.89      1672
weighted avg       0.95      0.95      0.95      1672



# descision tree is the good model

for both loan and spam model descison tree is performing well!

In [83]:
import numpy as np
a = np.ones(5)

In [84]:
a

array([1., 1., 1., 1., 1.])

In [85]:
d= a.tolist()

In [86]:
d

[1.0, 1.0, 1.0, 1.0, 1.0]

In [ ]:
a.